/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontEndUI;

import java.awt.event.ActionListener;
import mathbuddy.MathBuddy;
import observers.BeginObserver;

/**
 *
 * @author John Rosser
 */
public class MBSplash extends javax.swing.JFrame {

    ActionListener al;
    MathBuddy mb;
    
    
    /**
     * Creates new form MBSplash
     */
    public MBSplash(MathBuddy mb) {
        initComponents();
        this.mb = mb;
        this.al = new BeginObserver(this, IDField, mb);
        this.beginButton.addActionListener(al);
    }
    
    public String getName(){
        return this.IDField.getText();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IDField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        beginButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MathBuddy!");
        setName("MBSplash"); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 580));
        setResizable(false);
        getContentPane().setLayout(null);
        getContentPane().add(IDField);
        IDField.setBounds(310, 260, 193, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Name:");
        jLabel1.setFocusable(false);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(220, 260, 80, 30);

        beginButton.setText("Begin!");
        getContentPane().add(beginButton);
        beginButton.setBounds(510, 260, 80, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontEndUI/MathBuddyLogo.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 800, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDField;
    private javax.swing.JButton beginButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
