/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontEndUI;

import java.awt.event.ActionListener;
import mathbuddy.MathBuddy;
import observers.ReportQuitObserver;
import observers.ReportResetObserver;

/**
 *
 * @author John Rosser
 */
public class ReportScreen extends javax.swing.JFrame {

    /**
     * Creates new form ProblemScreen
     */
    ActionListener al;
    ActionListener newSetAL;
    MathBuddy mb;
    
    
    
    public ReportScreen(MathBuddy mb, int numCorrect) {
        initComponents();
        this.mb = mb;
        this.al = new ReportQuitObserver(this,mb);
        this.quitButton.addActionListener(al);
        this.newSetAL = new ReportResetObserver(mb, this);
        this.newSetButton.addActionListener(this.newSetAL);
        this.jLabel1.setText("You got " + numCorrect + " right out of 10!");
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        displayArea = new javax.swing.JPanel();
        quitButton = new javax.swing.JButton();
        newSetButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Math Buddy!");
        setAlwaysOnTop(true);
        setPreferredSize(new java.awt.Dimension(800, 580));
        setResizable(false);
        getContentPane().setLayout(null);

        displayArea.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        javax.swing.GroupLayout displayAreaLayout = new javax.swing.GroupLayout(displayArea);
        displayArea.setLayout(displayAreaLayout);
        displayAreaLayout.setHorizontalGroup(
            displayAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 556, Short.MAX_VALUE)
        );
        displayAreaLayout.setVerticalGroup(
            displayAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 95, Short.MAX_VALUE)
        );

        getContentPane().add(displayArea);
        displayArea.setBounds(110, 140, 560, 100);

        quitButton.setText("Quit");
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(quitButton);
        quitButton.setBounds(660, 440, 105, 25);

        newSetButton.setText("New set");
        getContentPane().add(newSetButton);
        newSetButton.setBounds(510, 440, 105, 25);

        jLabel1.setFocusable(false);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(46, 341, 452, 64);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frontEndUI/MathBuddy Result Background.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(1, 0, 970, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtonActionPerformed
        //System.exit(0);
    }//GEN-LAST:event_quitButtonActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel displayArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton newSetButton;
    private javax.swing.JButton quitButton;
    // End of variables declaration//GEN-END:variables
}
